// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using markdown.Server.Data;

#nullable disable

namespace markdown.Server.Migrations
{
    [DbContext(typeof(UserMarkdownDbContext))]
    partial class UserMarkdownDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("markdown.Shared.Models.Markdown", b =>
                {
                    b.Property<Guid>("MarkdownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MarkdownId");

                    b.ToTable("Markdowns");

                    b.HasData(
                        new
                        {
                            MarkdownId = new Guid("c2792f45-821e-4481-a129-fa6baf8a8b9e"),
                            Content = "# Hey, How are you doing?",
                            DateTime = new DateTime(2023, 1, 21, 19, 31, 35, 225, DateTimeKind.Local).AddTicks(8480),
                            UserId = new Guid("7663a9bf-8b7b-46e2-806e-8802749ff2a0")
                        });
                });

            modelBuilder.Entity("markdown.Shared.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7663a9bf-8b7b-46e2-806e-8802749ff2a0"),
                            Email = "email@email.com",
                            Password = "password",
                            UserName = "nassdaman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
